spring.application.name=Auth-server
app.jwt.public-key=${JWT_PUBLIC_KEY}
app.jwt.private-key=${JWT_PRIVATE_KEY}
#
app.jwt.issuer=${JWT_ISSUER:http://localhost:8080}
app.jwt.key-id=${JWT_KEY_ID:test-key}
app.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:60}
app.auth-server-url=${AUTH_SERVER_URL:http://localhost:8080}