spring.application.name=Auth-server
app.jwt.public-key=${JWT_PUBLIC_KEY}
app.jwt.private-key=${JWT_PRIVATE_KEY}
#
app.jwt.issuer=${JWT_ISSUER:auth-server}
app.jwt.key-id=${JWT_KEY_ID:test-key}
app.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:60}